scoreboard players add GoldRsC tick 1
execute as GoldRsC at @s[scores={tick=0}] anchored eyes run particle red_appear 0 100 0
execute as GoldRsC at @s[scores={tick=16}] anchored eyes run particle red_move_3 0 100 0
execute as GoldRsC at @s[scores={tick=32}] anchored eyes run particle red_move_-2 0 100 3
execute as GoldRsC at @s[scores={tick=64}] anchored eyes run particle red_move_-1 0 100 1
execute as GoldRsC at @s[scores={tick=80}] anchored eyes run particle red_move_3 0 100 0
execute as GoldRsC at @s[scores={tick=96}] anchored eyes run particle red_move_-6 0 100 3
execute as GoldRsC at @s[scores={tick=128}] anchored eyes run particle red_move_1 0 100 -3
execute as GoldRsC at @s[scores={tick=144}] anchored eyes run particle red_move_2 0 100 -2
execute as GoldRsC at @s[scores={tick=160}] anchored eyes run particle red_move_2 0 100 0
execute as GoldRsC at @s[scores={tick=184}] anchored eyes run particle red_move_1 0 100 2
execute as GoldRsC at @s[scores={tick=192}] anchored eyes run particle red_move_-1 0 100 3
execute as GoldRsC at @s[scores={tick=208}] anchored eyes run particle red_move_-1 0 100 2
execute as GoldRsC at @s[scores={tick=224}] anchored eyes run particle red_move_-1 0 100 1
execute as GoldRsC at @s[scores={tick=8}] anchored eyes run particle red_static_8 0 100 0
execute as GoldRsC at @s[scores={tick=24}] anchored eyes run particle red_static_8 0 100 3
execute as GoldRsC at @s[scores={tick=40}] anchored eyes run particle red_static_24 0 100 1
execute as GoldRsC at @s[scores={tick=72}] anchored eyes run particle red_static_8 0 100 0
execute as GoldRsC at @s[scores={tick=88}] anchored eyes run particle red_static_8 0 100 3
execute as GoldRsC at @s[scores={tick=104}] anchored eyes run particle red_static_24 0 100 -3
execute as GoldRsC at @s[scores={tick=136}] anchored eyes run particle red_static_8 0 100 -2
execute as GoldRsC at @s[scores={tick=152}] anchored eyes run particle red_static_8 0 100 0
execute as GoldRsC at @s[scores={tick=168}] anchored eyes run particle red_static_16 0 100 2
execute as GoldRsC at @s[scores={tick=200}] anchored eyes run particle red_static_8 0 100 2
execute as GoldRsC at @s[scores={tick=216}] anchored eyes run particle red_static_8 0 100 1
execute as GoldRsC at @s[scores={tick=232}] anchored eyes run particle red_change 0 100 0
execute as GoldRsC at @s[scores={tick=256}] anchored eyes run particle red_float_256 0 98 0
execute as GoldRsC at @s[scores={tick=255}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=255}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=259}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=259}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=267}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=267}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=271}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=271}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=275}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=275}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=283}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=283}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=287}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=287}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=291}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=291}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=299}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=299}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=303}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=303}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=307}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=307}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=311}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=311}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=315}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=315}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=319}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=319}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=323}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=323}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=331}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=331}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=335}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=335}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=339}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=339}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=347}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=347}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=351}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=351}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=355}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=355}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=363}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=363}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=367}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=367}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=371}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=371}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=375}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=375}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=379}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=379}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=383}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=383}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=387}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=387}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=395}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=395}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=399}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=399}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=403}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=403}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=411}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=411}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=415}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=415}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=419}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=419}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=427}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=427}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=431}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=431}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=435}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=435}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=439}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=439}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=447}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=447}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=463}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=463}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=479}] anchored eyes run particle white_rain_1 2 104 -8
execute as GoldRsC at @s[scores={tick=479}] anchored eyes run particle white_rain_2 2 104 8
execute as GoldRsC at @s[scores={tick=448}] anchored eyes run particle asriel_appear 1 101 0
execute as GoldRsC at @s[scores={tick=480}] anchored eyes run particle asriel_1float_32 1 101 0
execute as GoldRsC at @s[scores={tick=416}] anchored eyes run particle heart0_appear 0 101 0
execute as GoldRsC at @s[scores={tick=416}] anchored eyes run particle heart1_appear 0 101 0
execute as GoldRsC at @s[scores={tick=416}] anchored eyes run particle heart2_appear 0 101 0
execute as GoldRsC at @s[scores={tick=416}] anchored eyes run particle heart3_appear 0 101 0
execute as GoldRsC at @s[scores={tick=416}] anchored eyes run particle heart4_appear 0 101 0
execute as GoldRsC at @s[scores={tick=416}] anchored eyes run particle heart5_appear 0 101 0
execute as GoldRsC at @s[scores={tick=448}] anchored eyes run particle heart0_rotate 0 101 0
execute as GoldRsC at @s[scores={tick=448}] anchored eyes run particle heart1_rotate 0 101 0
execute as GoldRsC at @s[scores={tick=448}] anchored eyes run particle heart2_rotate 0 101 0
execute as GoldRsC at @s[scores={tick=448}] anchored eyes run particle heart3_rotate 0 101 0
execute as GoldRsC at @s[scores={tick=448}] anchored eyes run particle heart4_rotate 0 101 0
execute as GoldRsC at @s[scores={tick=448}] anchored eyes run particle heart5_rotate 0 101 0
execute as GoldRsC at @s[scores={tick=512}] anchored eyes run particle red_float_512 0 98 0
execute as GoldRsC at @s[scores={tick=512}] anchored eyes run particle asriel_8float_512 1 101 0

execute as GoldRsC at @s[scores={tick=512}] anchored eyes run particle asriel_8float_shadow_512 2.0 101 0

execute as GoldRsC at @s[scores={tick=512}] anchored eyes run particle background1_512 9 98 -4
execute as GoldRsC at @s[scores={tick=512}] anchored eyes run particle background2_512 9 98 4
