execute @a[scores={tick=-10..22}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=22..28}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=28..34}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=34..57}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=57..62}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=62..68}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=68..91}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=91..97}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=97..102}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=102..125}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=125..131}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=131..137}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=137..160}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=160..165}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=165..171}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=171..188}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=188..194}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=194..200}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=200..205}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=205..234}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=234..240}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=240..251}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=251..262}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=262..268}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=268..274}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=274..308}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=308..320}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=320..331}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=331..342}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=342..354}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=354..377}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=377..388}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=388..400}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=400..411}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=411..445}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=445..457}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=457..468}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=468..474}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=474..480}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=480..485}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=485..491}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=491..514}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=514..525}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=525..531}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=531..537}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=537..543}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=543..548}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=548..651}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=651..662}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=662..664}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=664..665}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=665..667}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=667..669}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=669..671}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=671..672}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=672..673}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=673..674}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=674..675}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=675..676}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=676..678}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=678..680}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=680..681}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=681..682}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=682..683}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=683..684}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=684..685}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=685..708}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=708..714}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=714..720}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=720..731}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=731..742}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=742..748}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=748..754}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=754..765}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=765..777}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=777..782}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=782..783}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=783..788}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=788..811}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=811..817}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=817..822}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=822..840}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=840..845}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=845..851}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=851..857}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=857..868}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=868..880}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=880..891}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=891..902}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=902..914}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=914..920}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=920..925}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=925..960}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=960..971}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=971..982}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=982..994}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=994..1005}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1005..1017}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1017..1028}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1028..1040}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1040..1051}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1051..1062}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1062..1074}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1074..1085}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1085..1108}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1108..1120}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1120..1131}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1131..1142}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1142..1154}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1154..1160}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1160..1165}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1165..1171}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1171..1177}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1177..1200}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1200..1205}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1205..1211}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1211..1234}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1234..1245}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1245..1251}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1251..1257}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1257..1262}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1262..1268}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1268..1325}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1325..1331}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1331..1337}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1337..1360}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1360..1365}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1365..1371}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1371..1394}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1394..1400}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1400..1405}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1405..1417}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1417..1428}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1428..1434}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1434..1440}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1440..1462}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1462..1468}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1468..1474}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1474..1491}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1491..1497}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1497..1502}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1502..1508}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1508..1531}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1531..1537}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1537..1542}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1542..1554}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1554..1565}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1565..1571}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1571..1577}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1577..1600}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1600..1605}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1605..1611}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1611..1622}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1622..1634}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1634..1645}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1645..1657}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1657..1668}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1668..1674}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1674..1680}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1680..1691}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1691..1702}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1702..1714}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1714..1788}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1788..1804}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1804..1828}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1828..1836}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1836..1843}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1843..1851}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1851..1883}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1883..1890}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1890..1897}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1897..1969}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=1969..1998}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=1998..2005}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=2005..2013}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=2013..2027}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=2027..2042}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=2042..2049}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=2049..2056}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=2056..2063}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=2063..2070}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=2070..2078}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=2078..2085}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=2085..2092}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
execute @a[scores={tick=2092..2099}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~0.2~~
execute @a[scores={tick=2099..2100}] ~~~ execute @e[type=armor_stand,tag=line] ~~~ tp @s ~~~0.2
